- name: chech a number is lessthan 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
  tasks:
  - name: print this if less that 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is less that 10"
    when: number | int < 10  #conditional expression
  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number is greather that or equal to 10"
    when: number | int >= 10  #condition statement    