- name: check and add expence user
  hosts: local
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER #here USer is avaible that gets ouptput of above cmd
    ignore_errors: True
    
  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}" 
