- name: install nginx
  become: yes
  hosts: web
  tasks:
  - name: print the status
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: installing nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: install nginx id Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"      
