- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: absent
    loop:
    - mysql
    - nginx
    - postfix
    - httpd  
