- name: Demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello {{ course | default ('Ansible') }}"

  - name: converting to uppercase
    vars:
      greeting: "Hello Nikhil"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: converting to lowercase
    vars:
      greeting: "Hello world"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"          