- name: Demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello {{ course | default ('Ansible') }}"

  - name: converting to uppercase
    vars:
      greeting: "Hello Nikhil"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: converting to lowercase
    vars:
      greeting: "Hello world"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: get the unique values
    vars:
      numbers: [1,2,3,45,6,1,2,3]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max
    vars:
      numbers: [1,2,4,56,76,98]
    ansible.builtin.debug:
      msg: " min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "DevOps with aws"
        duration: 120
        trainer: "Sivakkumar reddy"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert map to list
    vars:
      course:
      - {"key": "name","value": "DevOps with AWS" }
      - {"key": "duration","value": "Sivakumar Reddy" }
      - {"key": "Trainer","value": "items2dict" }
    ansible.builtin.debug:
      msg: {{ course | items2dict }}  