#! /bin/bash
- name: creating ec2 and r53 routers
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-08859a364ec730678 #reaplce with your subnet id in networks
    sg_id: sg-03e9711dd84e7c3ab #replace with yor sg id
    ami_id: ami-09c813fb71547fc4f #reaplace with your ami_id
    instances:
    - mysql
    - backend
    - frontend
    zone: 
  tasks:
  - name: creating ec2 instaces
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances